# Frappe Cloud Configuration for AspireHR

# .frappe_cloud.yml
app_name: aspirehr
app_title: AspireHR
description: Modern HR and Payroll Management System
repository: https://github.com/innopay-suresh/commi.git
branch: main

# Dependencies
dependencies:
  - frappe>=14.0.0

# Cloud-specific settings
cloud_settings:
  python_version: "3.10"
  node_version: "18"
  
# Environment variables (optional)
env_variables:
  ASPIRE_HR_VERSION: "1.0.0-dev"
  
# Custom domains (optional)
domains:
  - aspirehr.yourdomain.com
