version: '3.8'

services:
  aspirehr:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FRAPPE_SITE_NAME=aspirehr.docker
      - ADMIN_PASSWORD=admin
    stdin_open: true
    tty: true

# No separate Redis needed as it's included in the container
