version: '3.8'

services:
  aspirehr:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FRAPPE_SITE_NAME=aspirehr.docker
      - ADMIN_PASSWORD=admin
    depends_on:
      - redis
    volumes:
      - ./sites:/app/frappe-bench/sites
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  sites:
