name: Deploy AspireHR to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker build -t aspirehr:latest .
    
    - name: Test Docker image
      run: |
        docker run -d -p 8000:8000 --name aspirehr-test aspirehr:latest
        sleep 30
        curl -f http://localhost:8000 || exit 1
        docker stop aspirehr-test
    
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment triggered for Railway"
        # Railway automatically deploys from GitHub when connected
